// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./views/About/index.vue')['default']
    AppMain: typeof import('./views/Layout/components/AppMain/AppMain.vue')['default']
    Chart: typeof import('./components/Chart/chart.vue')['default']
    Foot: typeof import('./views/Layout/components/Foot/Foot.vue')['default']
    Home: typeof import('./views/Home/index.vue')['default']
    Introduce: typeof import('./views/Layout/components/Introduce/Introduce.vue')['default']
    Layout: typeof import('./views/Layout/index.vue')['default']
    'List.classic': typeof import('./components/List/list.classic.vue')['default']
    'List.virtual': typeof import('./components/List/list.virtual.vue')['default']
    Navbar: typeof import('./views/Layout/components/Navbar/Navbar.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/SvgIcon.vue')['default']
    Table: typeof import('./components/Table/table.vue')['default']
    Tpl: typeof import('./views/Tpl/index.vue')['default']
  }
}

export { }
