// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./views/About/index.vue')['default']
    AppMain: typeof import('./views/Layout/components/AppMain/AppMain.vue')['default']
    Banner: typeof import('./components/Banner/banner.vue')['default']
    Card_custom: typeof import('./components/Card/card_custom.vue')['default']
    Card_News: typeof import('./components/Card/card_News.vue')['default']
    Card_News_Effect: typeof import('./views/Expert/components/card_News_Effect.vue')['default']
    Chart: typeof import('./components/Chart/chart.vue')['default']
    CmsForm: typeof import('./components/Form/cmsForm.vue')['default']
    CustomService: typeof import('./views/CustomService/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Expert: typeof import('./views/Expert/index.vue')['default']
    Foot: typeof import('./views/Layout/components/Foot/Foot.vue')['default']
    Home: typeof import('./views/Home/index.vue')['default']
    Introduce: typeof import('./views/Layout/components/Introduce/Introduce.vue')['default']
    LangToggle: typeof import('./views/Layout/components/LangToggle/LangToggle.vue')['default']
    Layout: typeof import('./views/Layout/index.vue')['default']
    Navbar: typeof import('./views/Layout/components/Navbar/Navbar.vue')['default']
    Select: typeof import('./components/Select/select.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/svgIcon.vue')['default']
    Swiper: typeof import('./components/Swiper/swiper.vue')['default']
    System: typeof import('./views/System/index.vue')['default']
    Table: typeof import('./components/Table/table.vue')['default']
    Timeline: typeof import('./components/Timeline/timeline.vue')['default']
    Tpl: typeof import('./views/Tpl/index.vue')['default']
  }
}

export { }
