// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./components/Chart/chart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Index: typeof import('./views/Index/Index.vue')['default']
    'List.classic': typeof import('./components/List/list.classic.vue')['default']
    'List.virtual': typeof import('./components/List/list.virtual.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/SvgIcon.vue')['default']
    Swiper: typeof import('./views/Index/components/Swiper.vue')['default']
    Table: typeof import('./components/Table/table.vue')['default']
  }
}

export { }
